In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

In [11]:
data = pd.read_csv(r'C:\Users\212760357\Desktop\Boot_Camp\Project1\sociademic\social.csv')

In [12]:
data.head()

,Platform,country,month,year,total users,13-24,25-34,35-44,45-54,55-64,65 over,gender
0,Facebook,USA,March,2020,233500000,8.5,13.3,9.9,8.1,7.3,6.9,women
1,Facebook,USA,March,2020,233500000,8.0,13.7,9.0,6.4,4.7,4.2,men
2,Facebook,USA,February,2020,227800000,8.8,13.6,10.1,7.9,7.0,6.6,women
3,Facebook,USA,February,2020,227800000,8.1,13.6,8.8,6.6,4.8,4.1,men
4,Facebook,USA,January,2020,230700000,8.7,13.4,10.0,8.2,6.9,6.5,women